name: Update LeetCode README

on:
  push:
    branches:
      - "CPP-(C++)"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test workflow
        run: echo "Update README workflow is working!"
